### ISSUE TITLE
[Android] Unchecked exceptions' messages should be corrected

### ISSUE THREAD

**Issue by bartoszwilk** [dotintent/MultiPlatformBleAdapter#11]
IllegalStateExceptions messages syntax can be improved. Moreover we can inform user that he should call createClient first instead of informing about some unknown "BleManager".

[PR 1# discussion](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320879634)
[PR 2# discussion](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320882091)
[PR 3# discussion](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320882333)
[PR 4# discussion](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320882881)

**Comment by gmiszewski-intent** [comment]
Cleanup - closing old Issues. 
Please open new one if this is still valid.
