### ISSUE TITLE
[Android] Prevent from calling different callbacks at the same time

### ISSUE THREAD

**Issue by bartoszwilk** [dotintent/MultiPlatformBleAdapter#13]
We can think about preventing from calling success-success, success-error, error-success callbacks in places where we don't want such behavior.
[Related PR discussion](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320864028)

**Comment by gmiszewski-intent** [comment]
Cleanup - closing old Issues. 
Please open new one if this is still valid.
