### ISSUE TITLE
Backpressure strategy API

### ISSUE THREAD

**Issue by dariuszseweryn** [dotintent/MultiPlatformBleAdapter#48]
PR #45 has introduced a workaround for short-term bursts of notifications/indications that might cause `MissingBackpressureException` on Android OS. This exception is raised if a producer (of notifications) is quicker than the consumer (React Native bridge). On short* bursts it is possible to buffer all notifications and deliver them more slowly — however if the burst is prolonged an `OutOfMemoryException` may be expected.

`RxJava` which is the implementation detail of MBA implementation for Android allows for different backpressure strategies:
- buffer (as described above)
- drop — newest, overflown, emissions are dropped
- latest — oldest emissions are forgotten

Which strategy is the best fit for a particular application is unknown and there might be a need for exposing backpressure property to MBA API.

(Personally I do not think this issue has a high priority, we could wait if this behaviour will be requested by the users)

\* short — bursts containing less data that is possible to buffer in memory — YMMV

**Comment by chaitu18** [comment]
> PR #45 has introduced a workaround for short-term bursts of notifications/indications that might cause `MissingBackpressureException` on Android OS. This exception is raised if a producer (of notifications) is quicker than the consumer (React Native bridge). On short* bursts it is possible to buffer all notifications and deliver them more slowly — however if the burst is prolonged an `OutOfMemoryException` may be expected.
> 
> `RxJava` which is the implementation detail of MBA implementation for Android allows for different backpressure strategies:
> 
>     * buffer (as described above)
> 
>     * drop — newest, overflown, emissions are dropped
> 
>     * latest — oldest emissions are forgotten
> 
> 
> Which strategy is the best fit for a particular application is unknown and there might be a need for exposing backpressure property to MBA API.
> 
> (Personally I do not think this issue has a high priority, we could wait if this behaviour will be requested by the users)
> 
> * short — bursts containing less data that is possible to buffer in memory — YMMV

Hello dariuszseweryn,

I am getting this error "MissingBackpressureException" when monitorCharacteristicForService, Please see the code below.

`device.monitorCharacteristicForService(service, characteristicN, (error, characteristic) => {
                if (error) {
                    this.error(error)
                    return
                }
                this.handlePacket(characteristic.uuid, characteristic.value)
            })`

So for time being you want me to implement the changes you stated in my android Studio code? Please excuse if you find my post inappropriate as this is my very first post on github.

Thanks,

**Comment by chaitu18** [comment]
Hello dariuszseweryn,

I am getting this error "MissingBackpressureException" when monitorCharacteristicForService, Please see the code below.

`device.monitorCharacteristicForService(service, characteristicN, (error, characteristic) => { 
if (error) { 
this.error(error) return 
} 
this.handlePacket(characteristic.uuid, characteristic.value) 
})`

So for time being you want me to implement the changes you stated [here](https://github.com/Polidea/MultiPlatformBleAdapter/pull/45/files) in my android Studio code? Please excuse if you find my post inappropriate as this is my very first post on github.

Thanks,
