### ISSUE TITLE
[Android] Handling unsubscribe event while scanning for devices

### ISSUE THREAD

**Issue by bartoszwilk** [dotintent/MultiPlatformBleAdapter#6]
We should consider if we want to send an event/error when unsubscribing from scanning subscription.

[Related comment in PR](https://github.com/Polidea/MultiPlatformBleAdapter/pull/4#discussion_r320189410)

**Comment by gmiszewski-intent** [comment]
Cleanup - closing old Issues. 
Please open new one if this is still valid.
