### ISSUE TITLE
Consider adding support for Web Bluetooth API?

### ISSUE THREAD

**Issue by conhay** [dotintent/MultiPlatformBleAdapter#68]
Are there any plans to support the [Web Bluetooth API](https://webbluetoothcg.github.io/web-bluetooth/) with this adapter?

**Comment by jonsmirl** [comment]
Given that Expo is very close enabling direct support for react-native-ble-plx and given that Expo works cross-platform: Android, IOS and Web, there is definitively going to be a need for including Web Bluetooth support. Consider the need in PWAs -- progressive web apps.
