### ISSUE TITLE
Leaking BleAdapter

### ISSUE THREAD

**Issue by JamesMcIntosh** [dotintent/MultiPlatformBleAdapter#72]
If you create multiple clients when `FlutterBleLibPlugin.createClient()` overwrites the existing `BleAdapter`.

This means you can never destroy the previous clients, I'm pretty sure that this could cause a memory leaks as there are listeners attached etc.

**Comment by JamesMcIntosh** [comment]
move issue to Flutter plugin https://github.com/Polidea/FlutterBleLib/issues/563

**Comment by JamesMcIntosh** [comment]
The destroy method of BleModule leaks Subscriptions.

The leak is because of RxJava1's subscriptions to Observers holds strong references to the anonymous inner classes inside BleModule i.e onError and onNext.

More information: https://medium.com/@scanarch/how-to-leak-memory-with-subscriptions-in-rxjava-ae0ef01ad361

RxJava2 has the same sort of issue, need to check 3.0.0-beta branch
https://medium.com/@scanarch/how-to-leak-memory-with-disposables-in-rxjava2-715dd80bf966

**Comment by mikolak** [comment]
All subscriptions are cleared in `onDestroyClient()`
```java
    @Override
    public void destroyClient() {
        if (adapterStateChangesSubscription != null) {
            adapterStateChangesSubscription.unsubscribe();
            adapterStateChangesSubscription = null;
        }
        if (scanSubscription != null && !scanSubscription.isUnsubscribed()) {
            scanSubscription.unsubscribe();
            scanSubscription = null;
        }
        pendingTransactions.removeAllSubscriptions();
        connectingDevices.removeAllSubscriptions();

        discoveredServices.clear();
        discoveredCharacteristics.clear();
        discoveredDescriptors.clear();
        connectedDevices.clear();
        activeConnections.clear();
        discoveredDevices.clear();

        rxBleClient = null;
        IdGenerator.clear();
    }
```

Is this not sufficient?
