### ISSUE TITLE
Issues with iOS 15 SDK

### ISSUE THREAD

**Issue by below** [dotintent/MultiPlatformBleAdapter#79]
Due to [changes](https://developer.apple.com/documentation/corebluetooth/cbcharacteristic/1518728-service?changes=latest_minor) in the CoreBluetooth API, parts of the code break:

``` swift
…/RestoredState.swift:68:105: error: value of optional type 'CBPeripheral?' must be unwrapped to a value of type 'CBPeripheral'
                                                      peripheral: RxCBPeripheral(peripheral: $0.service.peripheral)),
                                                                                                        ^
```

``` swift
…/MultiplatformBleAdapter/iOS/RxBluetoothKit/RxCBCharacteristic.swift:59:52: error: value of optional type 'CBService?' must be unwrapped to a value of type 'CBService'
        return RxCBService(service: characteristic.service)
                                                   ^                                                      peripheral: RxCBPeripheral(peripheral: $0.service.peripheral)),
```

``` swift
…/RxCBDescriptor.swift:43:62: error: value of optional type 'CBCharacteristic?' must be unwrapped to a value of type 'CBCharacteristic'
        return RxCBCharacteristic(characteristic: descriptor.characteristic)
                                                             ^
```

**Comment by srgtuszy** [comment]
Thanks for contributing! PR has been merged

**Comment by georgeburduhos** [comment]
When maybe a release will be made here and on react-native-ble-plx?

**Comment by korykehl** [comment]
Hey @srgtuszy do you know of an eta of when this might make it into react-native-ble-plx?

**Comment by korykehl** [comment]
@georgeburduhos have you found a work around for this in the mean time?

**Comment by georgeburduhos** [comment]
> @georgeburduhos have you found a work around for this in the mean time?

Yes. If you run locally just follow the xcode instructions to fix the library. If you run on CI just make a sh script to replace the code needed to make the fix on each file

**Comment by below** [comment]
Here is what we did:
Change line 9 to: 
`  pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1. 9'`

In your main directory, execute:
`npx patch-package react-native-ble-plx --exclude 'android/build/|package.json$|.DS_Store$'`

This will create a patch  file in `patches/react-native-ble-plx+2.0.2.patch`

We had to go ahead and change `ios/Podfile.lock`to use `MultiplatformBleAdapter (0.1.9)` for the changes to be used in the Xcode project (if anyone has a better idea …)

I have created a push request for the 0.1.9 release [here](https://github.com/dotintent/MultiPlatformBleAdapter/pull/84), and once that is accepted will gladly do it for `react-native-ble-plx`

**Comment by menssen** [comment]
@below Thanks for publishing the fork with the new tag.

For some reason (I'm somewhat new to Cocoapods so I don't really understand the discrepancy), I had to patch this differently than what you described:

1. I added `pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1.9'` to *our* project's main Podfile.
2. I had to patch node_modules/react-native-ble-plx/react-native-ble-plx.podspec (just change 0.1.7 to 0.1.9)
3. node_modules/react-native-ble-plx/ios/Podfile seems to be irrelevant.

**Comment by wildseansy** [comment]
My patch file:
```
diff --git a/node_modules/react-native-ble-plx/react-native-ble-plx.podspec b/node_modules/react-native-ble-plx/react-native-ble-plx.podspec
index def210f..0a92dcc 100644
--- a/node_modules/react-native-ble-plx/react-native-ble-plx.podspec
+++ b/node_modules/react-native-ble-plx/react-native-ble-plx.podspec
@@ -17,5 +17,5 @@ Pod::Spec.new do |s|
   s.compiler_flags = '-DMULTIPLATFORM_BLE_ADAPTER'

   s.dependency 'React'
-  s.dependency 'MultiplatformBleAdapter', '0.1.7'
+  s.dependency 'MultiplatformBleAdapter', '0.1.9'
 end
```
> @below Thanks for publishing the fork with the new tag.
> 
> For some reason (I'm somewhat new to Cocoapods so I don't really understand the discrepancy), I had to patch this differently than what you described:
...
> 2. I had to patch node_modules/react-native-ble-plx/react-native-ble-plx.podspec (just change 0.1.7 to 0.1.9)
...

**Comment by below** [comment]
Whatever works for you ;) All I can hope the fix is accepted soon so we can stop patching …

**Comment by yeonwooz** [comment]
> @below Thanks for publishing the fork with the new tag.
> 
> For some reason (I'm somewhat new to Cocoapods so I don't really understand the discrepancy), I had to patch this differently than what you described:
> 
> 1. I added `pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1.9'` to _our_ project's main Podfile.
> 2. I had to patch node_modules/react-native-ble-plx/react-native-ble-plx.podspec (just change 0.1.7 to 0.1.9)
> 3. node_modules/react-native-ble-plx/ios/Podfile seems to be irrelevant.

Thank you!

If someone meets compatibility error, 


![image](https://user-images.githubusercontent.com/50320497/134804402-87dee2e8-eec0-4e8b-9495-bf04a380b7cc.png)

follow @menseen 's way and then try this

``` 
pod update
pod repo update
pod install
```

**Comment by diogoviannaaraujo** [comment]
@yeonwooz I've been trying to update to 0.1.9 but I keep getting that `None of your spec sources contain a spec satisfying the dependency: `MultiplatformBleAdapter (= 0.1.9)`.`

pod update, repo update and stuff did not work either.

**Comment by yeonwooz** [comment]
> @yeonwooz I've been trying to update to 0.1.9 but I keep getting that `None of your spec sources contain a spec satisfying the dependency: MultiplatformBleAdapter (= 0.1.9).`
> 
> pod update, repo update and stuff did not work either.

How about removing `Pods` directory and `Podfile.lock` and then try it again?

```
rm -rf Pods
rm -rf Podfile.lock
```

**Comment by dokinkon** [comment]
Please release 0.1.9 to cocoapods~

In FlutterBleLib, we can not specify git & tag in pod.spec. This really break down product release with Xcode 13 + iOS15

Thank you

**Comment by kofkgoing** [comment]
I don't understand why 0.1.9 pod is still not released.
Whose is MultiPlatformBleAdapter pod??
I tried to visit https://github.com/Polidea/MultiPlatformBleAdapter, 
but it was redirected to this repository.

pod search MultiPlatformBleAdapter --simple
-> MultiplatformBleAdapter (1.0.0-beta)
   An adapter for RxBluetoothKit that exposes consist API to crossplatform libraries
   pod 'MultiplatformBleAdapter', '~> 1.0.0-beta'
   - Homepage: https://github.com/Polidea/MultiPlatformBleAdapter
   - Source:   https://github.com/Polidea/MultiPlatformBleAdapter.git
   - Versions: 1.0.0-beta, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.0.4, 0.0.3, 0.0.2, 0.0.1 [cocoapods repo]
   - 1.0.0-beta, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.0.4, 0.0.3, 0.0.2, 0.0.1 [trunk repo]

**Comment by xiehui999** [comment]
> OK, I solved it by:
> 
> 1. using `pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1.9'` in `ios/Podfile`
> 2. In `node_modules/react-native-ble-plx/react-native-ble-plx.podspec` change 0.1.7 to 0.1.9

works for me
