### ISSUE TITLE
Release master branch as newest version

### ISSUE THREAD

**Issue by JaapWeijland** [dotintent/MultiPlatformBleAdapter#83]
Hi there, I'm sorry to ask this so directly as I know this is probably maintained by volunteers, but is it possible to release the version on `master` with an official tag? React Native repo's with a podspec containing this package can't point to the master branch but only to version tags. Since iOS 15, the latest version (0.1.8) of this package doesn't work anymore, and patching the dependent packages to include the master branch doesn't seem to be possible :(

**Comment by bhishakBitcanny** [comment]
+1

**Comment by mattahorton** [comment]
tagging @OfftheCode @dusker and @srgtuszy from dotinent. 

There's conversation in dotintent/MultiPlatformBleAdapter#84 about what needs to be done here and who. This is breaking a lot of our builds.

**Comment by dan714** [comment]
Same here.
