### ISSUE TITLE
Bump RxAndroidBle to support android 12

### ISSUE THREAD

**Issue by saty9** [dotintent/MultiPlatformBleAdapter#90]
The current version of RxAndroidBle (1.7) does not support new android 12 permissions so requires fine location permission unnecessarily. Version 1.13 and above fixes that https://github.com/dariuszseweryn/RxAndroidBle/pull/762.

**Comment by chge** [comment]
Apart from the new permission model, we've also experienced stability issues and crashes when building the app with `targetSdkVersion = 31`. And there's a 1st of August (1st of November) deadline for updating your target version: https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

In these circumstances, we really need a version of this lib that officially supports Android 12. Dear maintainers, please consider updating.

**Comment by fabiendem** [comment]
@dariuszseweryn Sorry to pull you in here, but I see all the work you did on https://github.com/dariuszseweryn/RxAndroidBle wrapped by this `MultiPlatformBleAdapter`, so maybe you have some insights.

To support Android 12 and the new permissions, the `MultiPlatformBleAdapter` needs to be updated, so the `react-native-ble-plx` library can be updated as well later.

Do you have any insights about the maintenance of `MultiPlatformBleAdapter`?
Should we consider the MultiPlatformBleAdapter and react-native-ble-plx projects dead?

Thanks
