### ISSUE TITLE
 module map file '/Users/t2b/Library/Developer/Xcode/DerivedData/blem2m-ecdewydnbimghkedqzzpibcfvgxw/Build/Intermediates.noindex/ArchiveIntermediates/blem2m/BuildProductsPath/Release-iphoneos/MultiplatformBleAdapter/MultiplatformBleAdapter.modulemap' not found

### ISSUE THREAD

**Issue by bhola-t2b** [dotintent/MultiPlatformBleAdapter#92]
module map file '/Users/t2b/Library/Developer/Xcode/DerivedData/blem2m-ecdewydnbimghkedqzzpibcfvgxw/Build/Intermediates.noindex/ArchiveIntermediates/blem2m/BuildProductsPath/Release-iphoneos/MultiplatformBleAdapter/MultiplatformBleAdapter.modulemap' not found

Working fine in android, ios debug but not working in ios release

**Comment by Bijiabo** [comment]
I have a similar problem, but it works on real device, error happens on iOS simulator

**Comment by Bijiabo** [comment]
> I have fixed this by making the ios version the same in Xcode and Podfile. so I am able to run it simulator and ios both devices.

update the `platform :ios` config?
